name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - beautifulsoup4  # Available via Conda
  - fastapi
  - uvicorn
  - ipykernel
  - bs4
  - faiss-cpu
  - wikipedia
  - python-dotenv
  - pip
  - pip:
    - streamlit
    - langchain_openai
    - langchain_core
    - langchain_community
    - langserve
    - pypdf
    - chromadb
    - groq
    - cassio
    - langchain-groq
    - arxiv
    - langchainhub
    - langchain
    - pysqlite3-binary
    - tree_sitter
    - tree_sitter_languages
    - sse_starlette
    - sentence_transformers
